# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Commit ID dosyasını oluştur
    sh("cd ../.. && npx tsx scripts/writeGit.ts")

    increment_build_number(xcodeproj: "fastlanetest.xcodeproj")

    # Xcode projesini build et
    build_app(
  workspace: "fastlanetest.xcworkspace",
  scheme: "fastlanetest",
  export_method: "app-store",
  export_options: {
    signingStyle: "manuel",
    provisioningProfiles: {
      "com.onatkilinc.fastlanetest" => "FastlaneTest"
    },
  }
)

    # TestFlight'a yükle
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
    )
  end
end

