# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and distribute APK to tester via transfer.sh"
  lane :beta do
    sh("cd ../.. && npx tsx scripts/writeGit.ts")
    sh("cd .. && ./gradlew clean")
    sh("cd .. && ./gradlew assembleRelease")

    commit_id = sh("git rev-parse --short HEAD").strip

    # APK yolunu ayarla
    apk_path = "../app/build/outputs/apk/release/app-release.apk"

    begin
      upload_output = sh("curl -s -F 'file=@#{apk_path}' https://file.io").strip
      upload_url = JSON.parse(upload_output)["link"]
    rescue JSON::ParserError => e
      UI.user_error!("❌ Dosya yüklenemedi. Gelen çıktı: #{upload_output}")
    end

    # Linki mail ile gönder (eğer mutt kuruluysa)
    sh("echo 'Yeni test build: #{upload_url} \nCommit: #{commit_id}' | mutt -s 'Android Test Build Link' -- onat.kilinc@orema.dev")
  end
end


